### PR TITLE
Adding universal build to Makefile

### PR DESCRIPTION
**Pull request by nestor-sk**
To use in the xcode and jenkins machines without intel/Mchip worries

### CODE REVIEW

**Review by uesteibar — DISMISSED** [review]

**Comment by nestor-sk** [comment]
@uesteibar I realised there as a possible problem :). If you want to look again and reapprove

**Review by omh — APPROVED** [review]
🚀

**Comment by uesteibar** [comment]
@nestor-sk what possible problem?

**Comment by uesteibar** [comment]
ah, I see, it's https://github.com/sketch-hq/gql-lint/pull/5/commits/d7d8772f0a77a8aae0e4801f49638b0647a9bcf9

LGTM

**Review by uesteibar — APPROVED** [review]

**Pull request merged**
